[package]
name = "db"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
command_handler = { path = "../command_handler" }
domain = { path = "../domain" }
event_store_core = { path = "../event_store_core" }
google-cloud-auth = { git = "https://github.com/bouzuya/google-cloud-rust", rev = "0b1c0108c28c22139a24638dbe95c92a0f0b769b" }
prost = "0.11.0"
prost-types = "0.11.1"
query_handler = { path = "../query_handler" }
thiserror = "1.0.32"
time = { version = "0.3.17", features = ["parsing", "formatting"] }
tokio = { version = "1.20.1", features = ["full"] }
tonic = { version = "0.8.2", features = ["tls", "tls-webpki-roots"] }
worker = { path = "../worker" }

[build-dependencies]
anyhow = "1.0.66"
prost-build = "0.11.1"
tonic-build = "0.8.2"

[dev-dependencies]
anyhow = "1.0.66"
