[package]
name = "db"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
event_store_core = { path = "../event_store_core" }
google-cloud-auth = { git = "https://github.com/googleapis/google-cloud-rust", rev = "b82d4462900db232b14029f69766e5016743fcc4" }
ordered-float = { version = "3.0.0", features = ["serde"] }
reqwest = { version = "0.11.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
time = { version = "0.3.14", features = ["parsing", "formatting"] }
tokio = { version = "1.20.1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["full"] }
