[package]
name = "bbn"
version = "0.36.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bbn-data = { workspace = true }
bbn-hatena-blog = { workspace = true }
bbn-repository = { workspace = true }
chrono = { workspace = true }
console = "0.14.1"
date-range = { workspace = true }
dialoguer = "0.8.0"
diff = "0.1.12"
hatena-blog-api = { workspace = true }
nom = { workspace = true }
open = "1.7.0"
pulldown-cmark = "0.9.2"
regex = "1.7.1"
serde = { workspace = true }
serde_json = { workspace = true }
sitemap-xml-writer = "0.1.0"
structopt = "0.3.21"
thiserror = { workspace = true }
tokio = { workspace = true }
xdg = "2.2.0"

[dev-dependencies]
assert_cmd = "1.0.4"
predicates = "2.0.2"
tempfile = { workspace = true }
