[package]
name = "adapter_fs"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
entity = { path = "../entity" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
use_case = { path = "../use_case" }

[dev-dependencies]
tempfile = "3.2.0"
