[package]
name = "adapter_fs"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
entity = { path = "../entity" }
limited-date-time = { git = "https://github.com/bouzuya/rust-limited-date-time", tag = "0.15.0" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
use_case = { path = "../use_case" }
query = { path = "../query" }

[dev-dependencies]
tempfile = "3.2.0"
