[package]
name = "use_case"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
entity = { path = "../entity" }
thiserror = "1.0.26"

[dev-dependencies]
anyhow = "1.0.43"
