[package]
name = "command_handler"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
domain = { path = "../domain" }
event_store_core = { path = "../event_store_core" }
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
worker_helper = { path = "../worker_helper" }

[dev-dependencies]
anyhow = { workspace = true }
