[package]
name = "firestore-path-helper-proc-macro"
version = "0.0.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"

[dev-dependencies]
firestore-path = "1.0.8"
trybuild = "1.0.110"

[lib]
proc-macro = true
