[package]
name = "use_case"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
domain = { path = "../domain" }
thiserror = "1.0.33"
