[package]
name = "grs"
version = "0.3.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
git2 = "0.13.20"
structopt = "0.3.22"
