[package]
name = "tasks"
version = "0.8.9"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
console = { path = "../console" }
entity = { path = "../entity" }
json = { path = "../json" }
use_case = { path = "../use_case" }

[dev-dependencies]
tempfile = "3.2.0"
