[package]
name = "suiro"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
termion = "1.5.6"
thiserror = "1.0.31"
