[package]
name = "tasks"
version = "0.8.3"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
chrono = "0.4.19"
dirs = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
entity = { path = "../entity" }
use_case = { path = "../use_case" }

[dev-dependencies]
tempfile = "3.2.0"
