[package]
name = "worker"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
command_handler = { path = "../command_handler" }
domain = { path = "../domain" }
event_store_core = { path = "../event_store_core" }
query_handler = { path = "../query_handler" }
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
thiserror = "1.0.33"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
anyhow = "1.0.65"
