[package]
name = "entity"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limited-date-time = { git = "https://github.com/bouzuya/rust-limited-date-time", version = "0.12.0" }
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.44"
