[package]
name = "query"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limited-date-time = { git = "https://github.com/bouzuya/rust-limited-date-time", version = "0.14.0" }
nom = "7.0.0"
thiserror = "1.0.29"

[dev-dependencies]
anyhow = "1.0.44"
