[package]
name = "adapter_console"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
entity = { path = "../entity" }
rustyline = "9.0.0"
use_case = { path = "../use_case" }
