[package]
name = "use_case"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
entity = { path = "../entity" }
nom = "7.0.0"
