[package]
name = "event-based-model"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
serde = { version = "1.0.227", features = ["derive"] }
thiserror = "2.0.16"
uuid = { version = "1.18.1", features = ["v4"] }

[dev-dependencies]
anyhow = "1.0.100"
rand = "0.9.2"
