[package]
name = "its"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
ulid = "0.5.0"

[dev-dependencies]
anyhow = "1.0.52"
assert_cmd = "2.0.2"
predicates = "2.1.0"
