[package]
name = "entity"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.28"
ulid = "0.4.1"

[dev-dependencies]
anyhow = "1.0.43"
