[package]
name = "enum-str-conv"
version = "0.0.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0.111"
