[package]
name = "import_twitter_data"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
domain = { path = "../domain" }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
time = { version = "0.3.17", features = ["parsing", "formatting"] }
