[package]
name = "import_twitter_data"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
domain = { path = "../domain" }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
