[package]
name = "bbn-repository"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
bbn-data = { workspace = true }
date-range = { workspace = true }
nom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
