[package]
name = "domain"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
event_store_core = { path = "../event_store_core" }
reqwest = { version = "0.11.11", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.33"
time = { version = "0.3.14", features = ["parsing", "formatting"] }
tokio = { version = "1.20.1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4", "serde"] }
