[package]
name = "b"
version = "0.11.1"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adapter_fs = { path = "../adapter_fs" }
anyhow = "1.0.41"
entity = { path = "../entity" }
limited-date-time = { git = "https://github.com/bouzuya/rust-limited-date-time", tag = "0.15.0" }
nom = "6.1.2"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
thiserror = "1.0.24"
use_case = { path = "../use_case" }
xdg = "2.4.0"

[dev-dependencies]
assert_cmd = "1.0.4"
predicates = "1.0.8"
tempfile = "3.2.0"
