[package]
name = "application"
version = "0.20.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adapter_sqlite = { path = "../adapter_sqlite" }
adapter_sqlite_query = { path = "../adapter_sqlite_query" }
anyhow = "1.0.52"
clap = { version = "3.1.8", features = ["derive"] }
domain = { path = "../domain" }
serde_json = "1.0.74"
tokio = { version = "1.15.0", features = ["full"] }
use_case = { path = "../use_case" }
xdg = "2.4.0"

[dev-dependencies]
anyhow = "1.0.52"
assert_cmd = "2.0.2"
predicates = "2.1.0"
tempfile = "3.3.0"
