[package]
name = "application"
version = "0.6.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adapter_fs = { path = "../adapter_fs" }
anyhow = "1.0.52"
argopt = "0.2.0"
domain = { path = "../domain" }
use_case = { path = "../use_case" }

[dev-dependencies]
anyhow = "1.0.52"
assert_cmd = "2.0.2"
predicates = "2.1.0"
