[package]
name = "blink"
version = "0.0.0"
edition = '2021'

[dependencies]
avr_delay = { git = "https://github.com/avr-rust/delay", rev = "b0c633c385af360d0d07742fcf3499f1a708ebcd" }
avr-config = "2.0.1"
avr-std-stub = "1.0"
avrd = "1.0.0"

[profile.release]
lto = true
