[package]
name = "iddd_a_and_es"
version = "0.0.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
ulid = "0.4.1"
