[package]
name = "date-time"
version = "0.11.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.44"
chrono = "0.4.19"
