[package]
name = "port"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entity = { path = "../entity" }
thiserror = "1.0.28"

[dev-dependencies]
anyhow = "1.0.43"
