[package]
name = "twiq-light"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
time = { version = "0.3.17", features = ["parsing", "formatting"] }
tokio = { version = "1.22.0", features = ["full"] }
