[package]
name = "weight"
version = "0.2.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"

[dev-dependencies]
assert_cmd = "1.0.5"
predicates = "1.0.8"
tempfile = "3.2.0"
