[package]
name = "weight"
version = "0.3.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.6", features = [ "attributes" ] }
async-trait = "0.1.50"
ordered-float = "2.5.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.5", features = ["runtime-async-std-native-tls", "sqlite"] }
structopt = "0.3.21"
thiserror = "1.0.25"

[dev-dependencies]
assert_cmd = "1.0.5"
predicates = "1.0.8"
tempfile = "3.2.0"
