[workspace]
members = ["crates/*"]

[patch.crates-io]
tonic-build = { git = "https://github.com/bouzuya/tonic", branch = "add-disable-comments" }

[workspace.dependencies]
anyhow = "1.0.68"
async-trait = "0.1.60"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["parsing", "formatting"] }
tokio = { version = "1.23.0", features = ["full"] }
tracing = "0.1.37"
