[package]
name = "yoh"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.95"
reqwest = { version = "0.12.12", default-features = false, features = ["cookies", "gzip", "rustls-tls"] }
tokio = { version = "1.43.0", features = ["full"] }
