[package]
name = "bbn-hatena-blog"
version = "0.0.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bbn-data = { workspace = true }
bbn-repository = { workspace = true }
date-range = { workspace = true }
hatena-blog-api = { workspace = true }
sqlx = { version = "0.5.5", features = ["runtime-tokio-rustls", "sqlite"] }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
