[package]
name = "query_handler"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
domain = { path = "../domain" }
thiserror = "1.0.37"
tracing = "0.1.37"
worker_helper = { path = "../worker_helper" }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { version = "1.21.2", features = ["full"] }
