[package]
name = "query_handler"
version = "0.0.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
domain = { path = "../domain" }
thiserror = { workspace = true }
tracing = { workspace = true }
worker_helper = { path = "../worker_helper" }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }
