[package]
name = "web"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
axum = "0.5.15"
db = { path = "../db" }
domain = { path = "../domain" }
query_handler = { path = "../query_handler" }
tokio = { version = "1.20.1", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
use_case = { path = "../use_case" }
worker = { path = "../worker" }

[dev-dependencies]
hyper = "0.14.20"
tower = { version = "0.4.13", features = ["util"] }
tower-http = { version = "0.3.4", features = ["add-extension"] }
