[package]
name = "yotei"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5.20", features = ["derive", "env"] }
google-cloud-auth = { version = "0.17.1", default-features = false, features = ["rustls-tls"] }
google-cloud-token = "0.1.2"
reqwest = { version = "0.12.8", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.131"
tokio = { version = "1.40.0", features = ["full"] }
