[package]
name = "week"
version = "0.2.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
date-range = { path = "../date-range/" }

[dev-dependencies]
assert_cmd = "1.0.4"
