[package]
name = "bbn-data"
version = "0.0.0"
authors = ["bouzuya <m@bouzuya.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
date-range = { workspace = true }
hatena-blog-api = { workspace = true }
thiserror = { workspace = true }
