name: bejson
on:
  push:
    branches: [master]
    paths:
      - "bejson/**"
      - ".github/workflows/bejson.yml"
    tags:
      - "bejson/*"
defaults:
  run:
    working-directory: bejson
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --verbose
      - run: cargo build --release --target ${{ matrix.target }} --verbose
      - uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bejson/target/${{ matrix.target }}/release/bejson
          asset_name: bejson-${{ matrix.target }}
          tag: ${{ github.ref }}
          overwrite: true
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
