name: date-to-week-date
on:
  push:
    branches:
      - "master"
    paths:
      - "date-to-week-date/**"
      - ".github/workflows/date-to-week-date.yml"
    tags:
      - "date-to-week-date/*"
defaults:
  run:
    working-directory: date-to-week-date
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --verbose
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
  deploy:
    # secrets:
    #   (GITHUB_TOKEN)
    #   DATE_TO_WEEK_DATE_GCP_PROJECT_ID
    #   DATE_TO_WEEK_DATE_GCP_REGION
    #   DATE_TO_WEEK_DATE_GCP_SERVICE
    #   DATE_TO_WEEK_DATE_GCP_SERVICE_ACCOUNT
    #   DATE_TO_WEEK_DATE_GCP_SERVICE_ACCOUNT_PRIVATE_KEY
    env:
      IMAGE_URL: ${{ secrets.DATE_TO_WEEK_DATE_GCP_REGION }}-docker.pkg.dev/${{ secrets.DATE_TO_WEEK_DATE_GCP_PROJECT_ID }}/${{ secrets.DATE_TO_WEEK_DATE_GCP_SERVICE }}/${{ secrets.DATE_TO_WEEK_DATE_GCP_SERVICE }}:${{ github.sha }}
    if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Deploy to GitHub Container Registry
      - uses: VaultVulp/gp-docker-action@1.5.0
        with:
          build-context: date-to-week-date/
          dockerfile: date-to-week-date/Dockerfile
          # extract-git-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: date-to-week-date
          image-tag: ${{ github.sha }}
      # Deploy to Google Artifact Registry & Cloud Run
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.DATE_TO_WEEK_DATE_GCP_SERVICE_ACCOUNT_PRIVATE_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1
      - run: |-
          gcloud auth configure-docker ${{ secrets.DATE_TO_WEEK_DATE_GCP_REGION }}-docker.pkg.dev
      - run: |-
          docker build -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}
      - run: |-
          gcloud run deploy ${{ secrets.DATE_TO_WEEK_DATE_GCP_SERVICE }} \
            --allow-unauthenticated \
            --image ${IMAGE_URL} \
            --max-instances "1" \
            --memory "1024Mi" \
            --platform "managed" \
            --quiet \
            --region ${{ secrets.DATE_TO_WEEK_DATE_GCP_REGION }} \
            --service-account ${{ secrets.DATE_TO_WEEK_DATE_GCP_SERVICE_ACCOUNT }} \
            --set-env-vars "BASE_PATH=/lab/date-to-week-date"
