name: date-range
on:
  push:
    branches: [master]
    paths:
      - "date-range/**"
      - ".github/workflows/date-range.yml"
defaults:
  run:
    working-directory: date-range
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --verbose
      - run: cargo test --verbose
