name: genuuid
on:
  push:
    branches:
      - "master"
    paths:
      - "genuuid/**"
      - ".github/workflows/genuuid.yml"
    tags:
      - "genuuid/*"
defaults:
  run:
    working-directory: genuuid
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --verbose
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
  deploy:
    if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          # set IMAGE_TAG
          image_tag=$(echo '${{ github.ref_name }}' | sed 's#genuuid/##')
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_ENV
          # set IMAGE_URL
          project_id="${{ secrets.GENUUID_GCP_PROJECT_ID }}"
          image_name="${{ secrets.GENUUID_GCP_SERVICE }}"
          image_url="gcr.io/${project_id}/${image_name}:${image_tag}"
          echo "IMAGE_URL=${image_url}" >> $GITHUB_ENV
      # deploy to GitHub Container Registry
      - uses: VaultVulp/gp-docker-action@1.5.0
        with:
          build-context: genuuid/
          dockerfile: genuuid/Dockerfile
          # extract-git-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: genuuid
          image-tag: ${{ env.IMAGE_TAG }}
      # Deploy to Google Container Registry & Cloud Run
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GENUUID_GCP_SERVICE_ACCOUNT_PRIVATE_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1
      - run: |-
          gcloud auth configure-docker
      - run: |-
          docker build -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}
      - run: |-
          gcloud run deploy ${{ secrets.GENUUID_GCP_SERVICE }} \
            --allow-unauthenticated \
            --args "server" \
            --image ${IMAGE_URL} \
            --max-instances "1" \
            --memory "1024Mi" \
            --platform "managed" \
            --quiet \
            --region ${{ secrets.GENUUID_GCP_REGION }} \
            --service-account ${{ secrets.GENUUID_GCP_SERVICE_ACCOUNT }} \
            --set-env-vars "BASE_PATH=/lab/genuuid"
