name: online-sitemap-builder
on:
  push:
    branches:
      - "master"
    paths:
      - "online-sitemap-builder/**"
      - ".github/workflows/online-sitemap-builder.yml"
    tags:
      - "online-sitemap-builder/*"
defaults:
  run:
    working-directory: online-sitemap-builder
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test --verbose
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
  deploy:
    if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          # set IMAGE_TAG
          image_tag=$(echo '${{ github.ref_name }}' | sed 's#online-sitemap-builder/##')
          echo "IMAGE_TAG=${image_tag}" >> $GITHUB_ENV
          # set IMAGE_URL
          region=${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_REGION }}
          project_id="${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_PROJECT_ID }}"
          repository="${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_SERVICE }}"
          image_name="${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_SERVICE }}"
          image_url="${region}-docker.pkg.dev/${project_id}/${repository}/${image_name}:${image_tag}"
          echo "IMAGE_URL=${image_url}" >> $GITHUB_ENV
      # deploy to GitHub Container Registry
      - uses: VaultVulp/gp-docker-action@1.5.0
        with:
          build-context: online-sitemap-builder/
          dockerfile: online-sitemap-builder/Dockerfile
          # extract-git-tag: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: online-sitemap-builder
          image-tag: ${{ env.IMAGE_TAG }}
      # Deploy to Google Container Registry & Cloud Run
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_SERVICE_ACCOUNT_PRIVATE_KEY }}"
      - uses: google-github-actions/setup-gcloud@v1
      - run: |-
          region=${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_REGION }}
          gcloud auth configure-docker ${region}-docker.pkg.dev
      - run: |-
          docker build --build-arg BASE_PATH=/lab/online-sitemap-builder -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}
      - run: |-
          gcloud run deploy ${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_SERVICE }} \
            --allow-unauthenticated \
            --image ${IMAGE_URL} \
            --max-instances "1" \
            --memory "1024Mi" \
            --platform "managed" \
            --quiet \
            --region ${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_REGION }} \
            --service-account ${{ secrets.ONLINE_SITEMAP_BUILDER_GCP_SERVICE_ACCOUNT }}
