[package]
name = "job"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
command_handler = { path = "../command_handler" }
db = { path = "../db" }
query_handler = { path = "../query_handler" }
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
worker_helper = { path = "../worker_helper" }
