[package]
name = "job"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.0.29", features = ["derive"] }
command_handler = { path = "../command_handler" }
db = { path = "../db" }
query_handler = { path = "../query_handler" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3.16"
worker_helper = { path = "../worker_helper" }
